2021-06-16-23-16-25  INFO       MainProcess  root inicio Wed Jun 16 23:16:25 2021
2021-06-16-23-17-21  INFO       MainProcess  root 10000/858701 Wed Jun 16 23:17:21 2021
2021-06-16-23-17-21  INFO       MainProcess  root actual rev date 2004-01-02
2021-06-16-23-19-55  INFO       MainProcess  root 20000/858701 Wed Jun 16 23:19:55 2021
2021-06-16-23-19-55  INFO       MainProcess  root actual rev date 2004-08-14
2021-06-16-23-24-57  INFO       MainProcess  root 30000/858701 Wed Jun 16 23:24:57 2021
2021-06-16-23-24-57  INFO       MainProcess  root actual rev date 2005-01-31
2021-06-16-23-32-51  INFO       MainProcess  root 40000/858701 Wed Jun 16 23:32:51 2021
2021-06-16-23-32-51  INFO       MainProcess  root actual rev date 2005-06-10
2021-06-16-23-43-39  INFO       MainProcess  root 50000/858701 Wed Jun 16 23:43:39 2021
2021-06-16-23-43-39  INFO       MainProcess  root actual rev date 2005-09-29
2021-06-17-00-22-37  INFO       MainProcess  root 60000/858701 Thu Jun 17 00:22:37 2021
2021-06-17-00-22-37  INFO       MainProcess  root actual rev date 2005-12-16
2021-06-17-00-36-10  INFO       MainProcess  root 70000/858701 Thu Jun 17 00:36:10 2021
2021-06-17-00-36-10  INFO       MainProcess  root actual rev date 2006-02-20
2021-06-17-00-49-50  INFO       MainProcess  root 80000/858701 Thu Jun 17 00:49:50 2021
2021-06-17-00-49-50  INFO       MainProcess  root actual rev date 2006-04-20
2021-06-17-01-06-30  INFO       MainProcess  root 90000/858701 Thu Jun 17 01:06:30 2021
2021-06-17-01-06-30  INFO       MainProcess  root actual rev date 2006-06-16
Traceback (most recent call last):
  File "mongo_to_mysql.py", line 80, in process
    cur.execute(eq_query, eq_insert_list)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'equation' at row 1")
Traceback (most recent call last):
  File "mongo_to_mysql.py", line 80, in process
    cur.execute(eq_query, eq_insert_list)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'equation' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mongo_to_mysql.py", line 103, in <module>
    main()
  File "mongo_to_mysql.py", line 100, in main
    process(sorted_revs_list)
  File "mongo_to_mysql.py", line 89, in process
    logging.error("error in page_id="+rev['page_id'] + " rev_id=" + rev['rev_id'])
TypeError: can only concatenate str (not "int") to str
